name: Terraform Infrastructure

on:
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: terraform-3tier

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: Terraform Init
        run: terraform init



      - name: Terraform Plan
        run: terraform plan 
        env:
          TF_VAR_db_password: ${{ secrets.DB_PASSWORD }}
          TF_VAR_db_username: ${{ secrets.DB_USERNAME }}
          TF_VAR_key_name: ${{ secrets.KEY_NAME }}

      - name: Terraform Apply
        run: terraform apply -auto-approve 
        env:
          TF_VAR_db_password: ${{ secrets.DB_PASSWORD }}
          TF_VAR_db_username: ${{ secrets.DB_USERNAME }}
          TF_VAR_key_name: ${{ secrets.KEY_NAME }}

      - name: Capture Terraform outputs
        id: tf
        run: |
          echo "web_ips=$(terraform output -json web_instance_ips)" >> $GITHUB_OUTPUT
          echo "app_ips=$(terraform output -json app_instance_ips)" >> $GITHUB_OUTPUT
          echo "rds=$(terraform output -raw rds_primary_endpoint)" >> $GITHUB_OUTPUT
          echo "pub_clb=$(terraform output -raw public_clb_dns)" >> $GITHUB_OUTPUT
          echo "int_clb=$(terraform output -raw internal_clb_dns)" >> $GITHUB_OUTPUT
          echo "web_sg=$(terraform output -raw web_sg_id)" >> $GITHUB_OUTPUT

      - name: Write outputs to GitHub Secrets
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          gh secret set WEB_INSTANCE_IPS --body '${{ steps.tf.outputs.web_ips }}'
          gh secret set APP_INSTANCE_IPS --body '${{ steps.tf.outputs.app_ips }}'
          gh secret set DB_HOST          --body "${{ steps.tf.outputs.rds }}"
          gh secret set PUBLIC_CLB_DNS   --body "${{ steps.tf.outputs.pub_clb }}"
          gh secret set INTERNAL_CLB_DNS --body "${{ steps.tf.outputs.int_clb }}"
          gh secret set WEB_SG_ID        --body "${{ steps.tf.outputs.web_sg }}"

      - name: Debug IPs
        run: |
          echo "WEB_IPS: ${{ secrets.WEB_INSTANCE_IPS }}"
          echo "APP_IPS: ${{ secrets.APP_INSTANCE_IPS }}"